/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using InetOptimizer.Types;

namespace InetOptimizer
{
    public class PKTNewProjectile
    {
        public PKTNewProjectile(BitReader reader)
        {
            projectileInfo = new ProjectileInfo(reader);
        }

        public ProjectileInfo projectileInfo { get; } = new ProjectileInfo();
    }
}